### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by ginop86** [Slicktone/GoFridge#1]
-I don't think we need a connection.js file inside config folder
-We need a Public folder with CSS and JS folders inside it.
-We need a Routes folder to handle all routes.

**Comment by Slicktone** [comment]
- [ ] I copied the same file structure from the sequelizedBurger homework and theres a connection.js file in there.  We'll need a general consensus on this.

- [ ] I made the Public Folder with a CSS folder.  I didn't make a JS folder, because that will be up to you and Bryant.  I'm not sure if we'll be using Handlebars or jQuery so that will be up to you guys.

- [ ] Routes folder and api-routes.js folder created as well - i didn't make a html-routes.js file for the same reason as above. ^
